// vue-examples/packages-method/src/App.vue
<style lang="scss">
  @import "../node_modules/ag-grid-community/src/styles/ag-grid.scss";
  @import "../node_modules/ag-grid-community/src/styles/ag-theme-alpine/sass/ag-theme-alpine.scss";

</style>

<template>
  <div>
    <button @click="getSelectedRows()">Get Selected Rows</button>
    <ag-grid-vue style="width: 500px; height: 500px;"
                 class="ag-theme-alpine"
                 :columnDefs="columnDefs"
                 :rowData="rowData"
                 rowSelection="multiple"
                 @grid-ready="onGridReady">
    </ag-grid-vue>
  </div>
</template>

<script>
  import {AgGridVue} from "ag-grid-vue";
  import 'ag-grid-enterprise';

  // set license key as follows
  import {LicenseManager} from 'ag-grid-enterprise';
  LicenseManager.setLicenseKey('Enter your license key');

  export default {
    name: 'App',
    data() {
      return {
        columnDefs: null,
        rowData: null,
        gridApi: null,
        columnApi: null,
      }
    },
    components: {
      AgGridVue
    },
    methods: {
      onGridReady(params) {
        this.gridApi = params.api;
        this.columnApi = params.columnApi;
      },
      getSelectedRows() {
        const selectedNodes = this.gridApi.getSelectedNodes();
        const selectedData = selectedNodes.map(node => node.data);
        const selectedDataStringPresentation = selectedData.map(node => node.make + ' ' + node.model).join(', ');
        alert(`Selected nodes: ${selectedDataStringPresentation}`);
      }
    },
    beforeMount() {
      this.columnDefs = [
        {headerName: 'Make', field: 'make'},
        {headerName: 'Model', field: 'model'},
        {headerName: 'Price', field: 'price'}
      ];

      fetch('https://raw.githubusercontent.com/ag-grid/ag-grid/master/grid-packages/ag-grid-docs/src/sample-data/rowData.json')
              .then(result => result.json())
              .then(rowData => this.rowData = rowData);
    }
  }
</script>

// angular-examples/packages-method/my-app/src/app/app.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AgGridAngular } from 'ag-grid-angular';
import 'ag-grid-enterprise';

// add license key as follows

import {LicenseManager} from 'ag-grid-enterprise';
LicenseManager.setLicenseKey('Enter your license key');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  @ViewChild('agGrid') agGrid: AgGridAngular;

  title = 'app';

  columnDefs = [
    {headerName: 'Model', field: 'model'},
    {headerName: 'Make', field: 'make', },
    {headerName: 'Price', field: 'price'}
  ];


  rowData: any;

  constructor(private http: HttpClient) {

  }

  ngOnInit() {
    this.rowData = this.http.get('https://raw.githubusercontent.com/ag-grid/ag-grid/master/grid-packages/ag-grid-docs/src/sample-data/rowData.json');
  }

  getSelectedRows() {
    const selectedNodes = this.agGrid.api.getSelectedNodes();
    const selectedData = selectedNodes.map( node => node.data );
    const selectedDataStringPresentation = selectedData.map( node => node.make + ' ' + node.model).join(', ');
    alert(`Selected nodes: ${selectedDataStringPresentation}`);
  }
}

<button (click)="getSelectedRows()">Get Selected Rows</button>

<ag-grid-angular
  #agGrid
  style="width: 500px; height: 500px;"
  class="ag-theme-alpine"
  [rowData]="rowData | async"
  [columnDefs]="columnDefs"
  rowSelection="multiple"
>
</ag-grid-angular>
