// angular-examples/packages-method/my-app/src/app/app.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AgGridAngular } from 'ag-grid-angular';
import 'ag-grid-enterprise';

// add license key as follows

import {LicenseManager} from 'ag-grid-enterprise';
LicenseManager.setLicenseKey('Enter your license key');

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  @ViewChild('agGrid') agGrid: AgGridAngular;

  title = 'app';

  columnDefs = [
    {headerName: 'Model', field: 'model'},
    {headerName: 'Make', field: 'make', },
    {headerName: 'Price', field: 'price'}
  ];


  rowData = [
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 }
  ];

  constructor(private http: HttpClient) {

  }

  getSelectedRows() {
    const selectedNodes = this.agGrid.api.getSelectedNodes();
    const selectedData = selectedNodes.map( node => node.data );
    const selectedDataStringPresentation = selectedData.map( node => node.make + ' ' + node.model).join(', ');
    alert(`Selected nodes: ${selectedDataStringPresentation}`);
  }
}

<button (click)="getSelectedRows()">Get Selected Rows</button>

<ag-grid-angular
  #agGrid
  style="width: 500px; height: 500px;"
  class="ag-theme-alpine"
  [rowData]="rowData | async"
  [columnDefs]="columnDefs"
  rowSelection="multiple"
>
</ag-grid-angular>

// react-examples/packages-method/src/App.jsx
import React, { Component } from 'react';
import './App.scss';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-enterprise';

// set license key as below
import {LicenseManager} from "ag-grid-enterprise";
LicenseManager.setLicenseKey('Enter your License Key');

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      columnDefs: [{
        headerName: "Make", field: "make"
      }, {
        headerName: "Model", field: "model"
      }, {
        headerName: "Price", field: "price"
      }],
      rowData: [{
        make: "Toyota", model: "Celica", price: 35000
      }, {
        make: "Ford", model: "Mondeo", price: 32000
      }, {
        make: "Porsche", model: "Boxter", price: 72000
      }]
    }
  }

  render() {
    return (
        <div
            className="ag-theme-alpine"
            style={{
              height: '500px',
              width: '600px' }}
        >
          <AgGridReact
              columnDefs={this.state.columnDefs}
              rowData={this.state.rowData}>
          </AgGridReact>
        </div>
    );
  }
}

export default App;
